config/routes.rb
Capres::Application.routes.draw do
  get "locations/index"
  get "main/index"
  resources :users
  get "/complaints" => "main#complaints", as: :complaints
  post "/save_complaint" => "main#save_complaint", as: :save_complaint

  # You can have the root of your site routed with "root"
  root 'main#index'

  namespace :admin do
    root 'main#index'
    resources :complaints
  end

  namespace :web do
    root 'main#index'
  end

  namespace :api do
    root 'main#index'
  end
end

app/models/bus_route.rb
class BusRoute < ActiveRecord::Base
	has_many :bus_states, dependent: :destroy
end

app/models/bus_state.rb
class BusState < ActiveRecord::Base
  belongs_to :bus_route
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin/base_controller.rb
module Admin
	class BaseController < ApplicationController
		layout 'admin'
		def index
		end
	end
end

app/controllers/admin/complaints_controller.rb
class Admin::ComplaintsController < ApplicationController
  before_action :set_admin_complaint, only: [:show, :edit, :update, :destroy]

  # GET /admin/complaints
  # GET /admin/complaints.json
  def index
    @admin_complaints = Complaint.all
  end

  # GET /admin/complaints/1
  # GET /admin/complaints/1.json
  def show
  end

  # GET /admin/complaints/new
  def new
    @admin_complaint = Complaint.new
  end

  # GET /admin/complaints/1/edit
  def edit
  end

  # POST /admin/complaints
  # POST /admin/complaints.json
  def create
    @admin_complaint = Complaint.new(admin_complaint_params)

    respond_to do |format|
      if @admin_complaint.save
        format.html { redirect_to @admin_complaint, notice: 'Complaint was successfully created.' }
        format.json { render action: 'show', status: :created, location: @admin_complaint }
      else
        format.html { render action: 'new' }
        format.json { render json: @admin_complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/complaints/1
  # PATCH/PUT /admin/complaints/1.json
  def update
    respond_to do |format|
      if @admin_complaint.update(admin_complaint_params)
        format.html { redirect_to @admin_complaint, notice: 'Complaint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @admin_complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/complaints/1
  # DELETE /admin/complaints/1.json
  def destroy
    @admin_complaint.destroy
    respond_to do |format|
      format.html { redirect_to admin_complaints_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_complaint
      @admin_complaint = Complaint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_complaint_params
      params[:admin_complaint]
    end
end

app/controllers/admin/main_controller.rb
module Admin
	class MainController < Admin::BaseController
	  def index
	  end

	  def create_route
	  	
	  end

	end
end

app/controllers/api/base_controller.rb
module Api
	class BaseController < ApplicationController
		layout 'api'
		responds :json
		def index
		end
	end
end

app/controllers/api/main_controller.rb
module Api
	class MainController < Api::BaseController
	  def index
	  end

	  def create_route
	  	
	  end

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
  end

  def add_location
  	
  end

  def remove_location
  	
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def complaints
  	@complaint = Complaint.new
  	@routes = BusRoute.all rescue []
  end

  def save_complaint
  	complaint = Complaint.new(complaint_params)
    respond_to do |format|
      if complaint.save
        format.html { redirect_to root_path, notice: 'Tu denuncia ha sido enviada exitosamente.' }
      else
        format.html { render action: "complaints" }
      end
    end
    
  end

  private
  	def complaint_params
  		params.require(:complaint).permit(:image, :name, :email, :phone, :description, :bus_route)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :lastname, :username, :email, :password)
    end
end

app/controllers/web/base_controller.rb
module Web
	class BaseController < ApplicationController
		layout 'web'
		def index
		end
	end
end

app/controllers/web/main_controller.rb
module Web
	class MainController < Web::BaseController
	  def index
	  end

	  def create_route
	  	
	  end

	end
end

app/helpers/admin/complaints_helper.rb
module Admin::ComplaintsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/complaints/_form.html.erb
<%= form_for(@admin_complaint) do |f| %>
  <% if @admin_complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_complaint.errors.count, "error") %> prohibited this admin_complaint from being saved:</h2>

      <ul>
      <% @admin_complaint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/complaints/edit.html.erb
<h1>Editing admin_complaint</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_complaint %> |
<%= link_to 'Back', admin_complaints_path %>

app/views/admin/complaints/index.html.erb
<h1>Listado de Denuncias</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>nombre</th>
      <th>email</th>
      <th>telefono</th>
      <th>Ruta de Autobus</th>
      <th>Fotografia</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @admin_complaints.each do |admin_complaint| %>
      <tr>
        <td><%= admin_complaint.name %></td>
        <td><%= admin_complaint.email %></td>
        <td><%= admin_complaint.phone %></td>
        <td><%= admin_complaint.bus_route %></td>
        <td><%= image_tag admin_complaint.image.url(:thumb) %></td>
        <td><%= link_to 'Show', admin_complaints_path, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_admin_complaint_path(admin_complaint), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', admin_complaint_path(admin_complaint), method: :delete, data: { confirm: 'Esta seguro que desea eliminar esta denuncia?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Complaint', new_admin_complaint_path, class: "btn btn-success" %>

app/views/admin/complaints/new.html.erb
<h1>New admin_complaint</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_complaints_path %>

app/views/admin/complaints/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_complaint_path(@admin_complaint) %> |
<%= link_to 'Back', admin_complaints_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="../../favicon.ico">

		<title>Admin Area</title>
		<!-- Bootstrap core CSS -->
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp" %>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Admin Area</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><a href="#">Rutas</a></li>
						<li><a href="#about">About</a></li>
						<li><a href="#contact">Contact</a></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Ruta Ciudadana</title>

    <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <% if controller.action_name == "index" %>
      <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp" %>
    <% end %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Rutas Ciudadanas", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Inicio</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

     <div class="container">

      <div class="starter-template">
        <input type="hidden" class="form-control" id="controller_action_name" value="<%=controller.action_name%>">
        <%= yield %>
        <%%>
       </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->
  </body>
</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Capres</title>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp" %>
  <%#= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBz-HwqAE71osXRPbQDuIVCeIIVsseelCE&sensor=true" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
</body>
</html>

app/views/layouts/web.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="../../favicon.ico">

		<title>Web Area</title>
		<!-- Bootstrap core CSS -->
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp" %>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Web Area</a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><a href="#">Rutas</a></li>
						<li><a href="#about">About</a></li>
						<li><a href="#contact">Contact</a></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</div>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/locations/index.html.erb
<h1>Locations#index</h1>
<p>Find me in app/views/locations/index.html.erb</p>

app/views/main/complaints.html.erb
<%= form_for @complaint, url: save_complaint_path(@complaint), html: { id: "complaints-form", role: "form", :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :name, "Nombre" %>
    <%= f.text_field :name, placeholder: "Nombre", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email, "Direccion de correo" %>
    <%= f.text_field :email, placeholder: "Direccion de correo", class: "form-control", type: :email %>
  </div>
  <div class="form-group">
    <%= f.label :phone, "Numero de telefono" %>
    <%= f.text_field :phone, placeholder: "Numero de telefono", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bus_route, "Numero de ruta" %>
    <%= f.select :bus_route, options_for_select(@routes.map{|route| route.name}), {class: "form-control"}, :include_blank => true %>
  </div>
  <div class="form-group">
    <%= f.label :description, "descripcion de la denuncia" %>
    <%= f.text_field :description, placeholder: "descripcion de la denuncia", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image, "Fotografia" %>
    <%= f.file_field :image %>
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <%= f.submit "enviar denuncia", class: "btn btn-default" %>
<% end %>

app/views/main/index.html.erb
<h1>Ruta Ciudadana</h1>
<p class="lead">Mostrando las ubicaciones de las rutas de autobuses</p>
<div id="map-canvas" />

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.lastname %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>